version: '2'

services:
  draw-image-export:
    image: hub.qucheng.com/app/draw-image-export:1.0.1-20220825
    container_name: draw-image-export
    ports:
      - '8000:8000'
    environment:
      - DRAWIO_SERVER_URL=http://drawio:8080
      - DEBUG=1
      - IS_CONTAINER=true
    networks:
      - net

  drawio:
    image: hub.qucheng.com/app/drawio:${TAG:-latest}
    container_name: drawio
    ports:
      - '8080:8080'
    depends_on:
      - draw-image-export
    environment:
      - EXPORT_URL=http://draw-image-export:8000
      - DRAWIO_BASE_URL=http://demo.haogs.cn
      - DEBUG=1
      - IS_CONTAINER=true
    networks:
      - net

networks:
  net:
    driver: bridge

