#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libfs.sh

# Load Global/Apache/PHP environment variables
. /etc/s6/s6-init/envs

#=====================#
#   Prepare PHP       #
#=====================#
PRE_CFG="/usr/local/tomcat/webapps/draw/js/PreConfig.js"

info "Render PreConfig.js with environment variables."
sed -i "s/__APP_DOMAIN__/$APP_DOMAIN/" $PRE_CFG